name: Test releases

on:
  push:
    branches:
      - main

jobs:
  create_release:
    name: Create release and publish
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.head_commit.message, 'chore(release)') && !contains(github.event.head_commit.message, '[skip ci]')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: build integrations
        run: npm run build

      - name: Zip integrations
        run: npm run build:zip

      - name: Create GitHub release
        run: node ./scripts/action-zip.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
